name: pull request review requested notification
on:
  pull_request:
    types: [review_requested]
    branches:
    - main

jobs: 
  notify:
    name: notify
    runs-on: ubuntu-latest
    # т.к ревьюверы ставятся автоматически при открытии ПР, а action срабатывает на каждый реквест, 
    # нужно понять, что мы запрашиваем ревью вручную после того как ПР открыт. 
    # Для этого проверяем наличие assignee(ставится при открытии после установки ревьюверов)
    if: ${{ github.event.pull_request.assignee != null }}
    steps:
      - name: send telegram message on PR
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            👁👁👁
            PR от ${{ github.event.pull_request.user.login }}
            
            ${{ github.event.pull_request.title }}
            
            👨👨👨 требует ревью от ${{ fromJson(SECRETS.TELEGRAM_ACCOUNTS)[github.event.requested_reviewer.login] }}
            
            ${{ github.event.pull_request.html_url }}
            
