name: Pull request title lint
on:
  pull_request:
    branches: [main]
    types: ['opened', 'edited', 'reopened']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install Dependencies
        run: npm i
      - name: Lint title
        uses: JulienKode/pull-request-name-linter-action@v0.5.0
